# ----------- CONFIGURABLE START -----------
title:            JonLuca's Blog
description:      JonLuca's Blog - A blog about tech, programming, and information
url:              https://blog.jonlu.ca # Site url, without a slash at the end.
signoff:          "JonLuca" # Your name
markdown: kramdown
twitter_username: jonluca
encoding: utf-8
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-brotli
exclude:
  - core
  - node_modules
links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Contact
    url:          /contact
    external:     false
permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

sass:
  style: compressed

timezone: America/Los_Angeles
keep_files:
  - 'images'
zopfli:
  extensions:
    - '.html'
    - '.css'
    - '.js'
    - '.svg'
    - '.txt'
    - '.ttf'
    - '.atom'
    - '.stl'
    - '.xml'
    - '.jpg'
    - '.png'
    - '.eot'
    - '.wav'
    - '.webp'

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:
    harmony: true
